version: '3.8'

services:
  addition_service:
    build: ./addition_service
    ports:
      - "8001:8000"

  subtraction_service:
    build: ./subtraction_service
    ports:
      - "8002:8000"

  multiplication_service:
    build: ./multiplication_service
    ports:
      - "8003:8000"

  division_service:
    build: ./division_service
    ports:
      - "8004:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - addition_service
      - subtraction_service
      - multiplication_service
      - division_service

  monolith_app:
    build: ./monolith
    ports:
      - "81:8000"
